#' officedown: 'R Markdown' Format for 'Microsoft' Documents
#'
#' The package `officedown` allows production of corporate documents from ‘R Markdown’ by reusing
#' formatting defined in ‘Microsoft Word’ documents. You can reuse table styles,
#' list styles but also add column sections, landscape oriented pages. Table and
#' image captions as well as cross-references are transformed into ‘Microsoft Word’
#' fields, allowing documents edition and merging without mis-referencing issues;
#' the syntax conforms to the ‘bookdown’ cross-reference definition. Objects
#' generated by the ‘officer’ package are also supported in the ‘knitr’ chunks.
#'
#' ‘Microsoft PowerPoint’ presentations also benefit from this as well as the
#' ability to produce editable vector graphics in PowerPoint.
#'
#' To learn more about officer, start with the vignettes:
#' `browseVignettes(package = "officedown")`
#'
#' @seealso \url{https://ardata-fr.github.io/officedown}
#' @docType package
#' @name officedown
NULL
